//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QDLogistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdminUsers()
        {
            this.TimeZone = 0;
        }
    
        public bool IsEnable { get; set; }
        public bool IsVisible { get; set; }
        public int Id { get; set; }
        public int GroupId { get; set; }
        public string Name { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string ApiUserName { get; set; }
        public string ApiPassword { get; set; }
        public string Warehouse { get; set; }
        public int TimeZone { get; set; }
        public string Auth { get; set; }
        public Nullable<System.DateTime> LLT { get; set; }
        public bool IsLogin { get; set; }
    
        public virtual AdminGroups AdminGroups { get; set; }
    }
}
