//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QDLogistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseEvent
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public int PackageID { get; set; }
        public string LabelID { get; set; }
        public string NewLabelID { get; set; }
        public int MethodID { get; set; }
        public byte Type { get; set; }
        public byte Request { get; set; }
        public byte Status { get; set; }
        public System.DateTime Create_at { get; set; }
        public Nullable<System.DateTime> Request_at { get; set; }
        public Nullable<System.DateTime> Response_at { get; set; }
        public int Update_by { get; set; }
    
        public virtual Packages Packages { get; set; }
    }
}
