//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QDLogistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirectLine
    {
        public bool IsEnable { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public string Abbreviation { get; set; }
        public string ContactName { get; set; }
        public string CompanyName { get; set; }
        public string PhoneNumber { get; set; }
        public string CountryName { get; set; }
        public string CountryCode { get; set; }
        public string City { get; set; }
        public string StreetLine1 { get; set; }
        public string StreetLine2 { get; set; }
        public string StateName { get; set; }
        public string PostalCode { get; set; }
    }
}
