//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QDLogistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Items()
        {
            this.DeclaredValue = 0m;
            this.BundleItems = new HashSet<BundleItems>();
            this.SerialNumbers = new HashSet<SerialNumbers>();
        }
    
        public Nullable<bool> IsEnable { get; set; }
        public int ID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> PackageID { get; set; }
        public string SKU { get; set; }
        public string OriginalSKU { get; set; }
        public string ProductID { get; set; }
        public string ProductIDOriginal { get; set; }
        public string ProductIDRequest { get; set; }
        public decimal DeclaredValue { get; set; }
        public decimal DLDeclaredValue { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> QtyReturned { get; set; }
        public Nullable<int> QtyShipped { get; set; }
        public string DisplayName { get; set; }
        public Nullable<decimal> LineTotal { get; set; }
        public Nullable<int> KitItemCount { get; set; }
        public string eBayItemID { get; set; }
        public string eBayTransactionId { get; set; }
        public string SalesRecordNumber { get; set; }
        public Nullable<int> BackOrderQty { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> ShipFromWarehouseID { get; set; }
        public Nullable<int> ReturnedToWarehouseID { get; set; }
        public Nullable<double> Weight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BundleItems> BundleItems { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Packages Packages { get; set; }
        public virtual Warehouses ReturnWarehouses { get; set; }
        public virtual Warehouses ShipWarehouses { get; set; }
        public virtual Skus Skus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SerialNumbers> SerialNumbers { get; set; }
    }
}
