//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QDLogistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Packages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Packages()
        {
            this.UploadTracking = true;
            this.CaseEvent = new HashSet<CaseEvent>();
            this.Items = new HashSet<Items>();
        }
    
        public Nullable<bool> IsEnable { get; set; }
        public int ID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> OrderItemID { get; set; }
        public Nullable<int> BundleItemID { get; set; }
        public byte ProcessStatus { get; set; }
        public bool ProcessBack { get; set; }
        public decimal DeclaredTotal { get; set; }
        public decimal DLDeclaredTotal { get; set; }
        public int DLCurrency { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public string ShippingMethodName { get; set; }
        public string ShippingServiceCode { get; set; }
        public Nullable<int> ShippingMethod { get; set; }
        public Nullable<int> FirstMile { get; set; }
        public Nullable<byte> Export { get; set; }
        public Nullable<byte> ExportMethod { get; set; }
        public Nullable<System.DateTime> EstimatedDeliveryDate { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
        public Nullable<System.DateTime> FirstMilePickupDate { get; set; }
        public Nullable<System.DateTime> FirstMileArrivalDate { get; set; }
        public Nullable<System.DateTime> ScanDateA { get; set; }
        public Nullable<System.DateTime> ScanDateB { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<int> DeliveryStatus { get; set; }
        public string DeliveryNote { get; set; }
        public string WinitNo { get; set; }
        public string BoxID { get; set; }
        public string TagNo { get; set; }
        public Nullable<decimal> FinalShippingFee { get; set; }
        public bool UploadTracking { get; set; }
        public string TrackingNumber { get; set; }
        public int WorkDays { get; set; }
        public bool NeedInsurance { get; set; }
        public Nullable<int> POId { get; set; }
        public string POInvoice { get; set; }
        public Nullable<int> RMAId { get; set; }
        public string FilePath { get; set; }
        public string Comment { get; set; }
        public string SupplierComment { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
    
        public virtual Box Box { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaseEvent> CaseEvent { get; set; }
        public virtual DirectLineLabel Label { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Items> Items { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual ShippingMethod Method { get; set; }
        public virtual ShippingMethod FirstMethod { get; set; }
    }
}
