//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QDLogistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PickProduct()
        {
            this.IsEnable = true;
            this.IsPicked = false;
            this.IsMail = false;
            this.QtyPicked = 0;
        }
    
        public bool IsEnable { get; set; }
        public bool IsPicked { get; set; }
        public bool IsMail { get; set; }
        public int ID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> PackageID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public string UPC { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public Nullable<int> Qty { get; set; }
        public int QtyPicked { get; set; }
        public Nullable<System.DateTime> PickUpDate { get; set; }
        public Nullable<int> PickUpBy { get; set; }
    }
}
