//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QDLogistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseItemReceive
    {
        public bool IsRequireSerialScan { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> OrderItemID { get; set; }
        public string ProductID { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> PurchaseID { get; set; }
        public Nullable<int> PurchaseReceiveID { get; set; }
        public Nullable<int> RMAId { get; set; }
        public Nullable<int> CreditMemoID { get; set; }
        public string CreditMemoReason { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public string WarehouseName { get; set; }
        public Nullable<int> LocationBinID { get; set; }
        public string BinName { get; set; }
    }
}
