//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QDLogistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SerialNumberForRefundLabel
    {
        public bool IsUsed { get; set; }
        public int ID { get; set; }
        public int oldOrderID { get; set; }
        public Nullable<int> newOrderID { get; set; }
        public string oldLabelID { get; set; }
        public string newLabelID { get; set; }
        public int RMAID { get; set; }
        public string Sku { get; set; }
        public string SerialNumber { get; set; }
        public int WarehouseID { get; set; }
        public System.DateTime Create_at { get; set; }
    }
}
