//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QDLogistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SerialNumbers
    {
        public Nullable<int> OrderID { get; set; }
        public string ProductID { get; set; }
        public string SerialNumber { get; set; }
        public int OrderItemID { get; set; }
        public Nullable<int> KitItemID { get; set; }
    
        public virtual Items Items { get; set; }
    }
}
