//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QDLogistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Skus()
        {
            this.Origin = "CN";
            this.BundleItems = new HashSet<BundleItems>();
            this.Items = new HashSet<Items>();
            this.ShadowSku = new HashSet<Skus>();
        }
    
        public Nullable<bool> IsEnable { get; set; }
        public string Sku { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public string ParentShadow { get; set; }
        public string ParentKit { get; set; }
        public string UPC { get; set; }
        public string Origin { get; set; }
        public Nullable<int> Brand { get; set; }
        public Nullable<bool> Battery { get; set; }
        public Nullable<byte> Export { get; set; }
        public Nullable<byte> ExportMethod { get; set; }
        public string PurchaseInvoice { get; set; }
        public int Weight { get; set; }
        public int ShippingWeight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BundleItems> BundleItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Items> Items { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual ProductType ProductType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Skus> ShadowSku { get; set; }
        public virtual Skus ParentSku { get; set; }
    }
}
