//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QDLogistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Warehouses()
        {
            this.WarehouseType = 0;
            this.ReturnWarehouses = new HashSet<Items>();
            this.ShipWarehouses = new HashSet<Items>();
        }
    
        public Nullable<bool> IsEnable { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<bool> IsSellable { get; set; }
        public Nullable<bool> AllowUseQtyForFBAShipments { get; set; }
        public Nullable<bool> EnforceBins { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string QBWarehouseName { get; set; }
        public Nullable<int> WarehouseType { get; set; }
        public string WinitWarehouseID { get; set; }
        public string DropShipCentralWarehouseCode { get; set; }
        public string CarrierData { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Items> ReturnWarehouses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Items> ShipWarehouses { get; set; }
    }
}
